# 建表
#spring:
#  datasource:
#    url: jdbc:mysql://192.168.10.30:3306/datasource1
#    username: workflow
#    password: 123456
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    type: com.alibaba.druid.pool.DruidDataSource
#    druid:
#      # 数据源初始化大小
#      initial-size: 1
#      # 数据源最小存活数
#      min-idle: 1
#      # 数据源最大活跃数
#      max-active: 20
#      # 数据源最大空闲时间，单位为毫秒。如果空闲时间大于该值，则连接被归还到连接池时将被关闭
#      max-idle: 10000
#      # 数据源最大配置的等待时间，单位为毫秒。如果超过这个值则请求失败
#      max-wait: 10000

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    datasource1:
      url: jdbc:mysql://192.168.10.30:3306/datasource1?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF8&useSSL=false
      username: workflow
      password: 123456
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      driver-class-name: com.mysql.cj.jdbc.Driver
    datasource2:
      url: jdbc:mysql://192.168.10.30:3306/datasource2?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF8&useSSL=false
      username: workflow
      password: 123456
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      driver-class-name: com.mysql.cj.jdbc.Driver

